version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - post_db:/data/db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back_net:
        aliases:
          - post_db

  comment_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - comment_db:/data/db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      back_net:
        aliases:
          - comment_db

  ui:
#    build: ./ui
    image: ${USERNAME_HUB}/ui:${SERVICE_VER}
    ports:
      - 80:9292/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - ui

  post:
#    build: ./post-py
    image: ${USERNAME_HUB}/post:${SERVICE_VER}
    container_name: post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post 
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post

  comment:
#    build: ./comment
    image: ${USERNAME_HUB}/comment:${SERVICE_VER}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - comment        
      back_net:
        aliases:
          - comment

volumes:
  post_db:
  comment_db:    

networks:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${FRONT_NET_SUBNET}
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${BACK_NET_SUBNET}

