---
- name: Docker Install
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      apt:
        update_cache: yes
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - gnupg
        state: present

    - name: Add Docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker Engine
      apt:
        update_cache: yes
        name:
        - docker-ce=5:18.09.0~3-0~ubuntu-bionic
        - docker-ce-cli=5:18.09.0~3-0~ubuntu-bionic
        - containerd.io=1.2.0-1

    - name: Install Docker module for Python
      pip:
        name: docker
